### ISSUE TITLE
Release crate on crates.io

### ISSUE THREAD

**Issue by robinhundt** [ZenGo-X/rust-paillier#15]
As discussed in #13 this crate is ready to be released on [crates.io](https://crates.io).
Proposed name: `kzen-pallier`

**Comment by survived** [comment]
Done! https://crates.io/crates/kzen-paillier

We also configured travis to automatically upload a new version on crates.io so it will always be up-to-date

**Comment by survived** [comment]
Tip: preferred way to include crate into your project is:

```toml
[dependencies.kzen-paillier]
package = "paillier"
version = "0.4"
```

So you can use shorter name `paillier` in the code, instead of `kzen_paillier`
